// Generated by CoffeeScript 1.8.0
(function() {
  var o, sms;

  sms = require('../lib/sms');

  o = {
    "uid": "1001@500883280001",
    "password": "30250B31F881FA5D7F376485D11E6534",
    "sendURL": "http://smsapi.c123.cn/OpenPlatform/OpenApi",
    "checkURL": "http://smsapi.c123.cn/OpenPlatform/OpenApi?action=getBalance&ac=1001@500883280001&authkey=30250B31F881FA5D7F376485D11E6534"
  };

  sms.config(o);

  sms.left(function(err, result) {
    return console.log(err, result);
  });

}).call(this);
