// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var API, Dict, EventProxy, Token, User, api, appid, auth, getConfig, getToken, get_js_sdk_ticket, home_url, host, inTime, logger, menu, models, moment, request, saveToken, save_js_sdk_ticket, secret;

  auth = require('../lib/auth');

  API = require('wechat-api');

  appid = 'wx1f9fe13fd3655a8d';

  secret = '2a3792094fc7e3b91a4920a8afb0a0c1';

  models = require('../models/index');

  User = models.User;

  Token = models.Token;

  Dict = models.Dict;

  EventProxy = require('eventproxy');

  logger = require('log4js').getDefaultLogger();

  request = require('request');

  moment = require('moment');

  getToken = function(cb) {
    return Token.findOne({
      appid: appid
    }, function(err, result) {
      if (err) {
        logger.error('GetTokenError:' + err);
        return cb(null, null);
      } else if (result) {
        if (new Date().getTime() - result.get_ts.getTime() < 300000) {
          return cb(null, {
            accessToken: result.token
          });
        } else {
          return cb(null, null);
        }
      } else {
        return cb(null, null);
      }
    });
  };

  saveToken = function(token, cb) {
    return Token.findOne({
      appid: appid
    }, function(err, result) {
      if (err) {
        cb(null, null);
        return logger.error('SaveTokenError:' + err);
      } else if (result && result.token) {
        result.token = token.accessToken;
        result.get_ts = new Date();
        return result.save(cb);
      } else {
        token = new Token({
          appid: appid,
          secret: secret,
          token: token.accessToken,
          get_ts: new Date()
        });
        return token.save(cb);
      }
    });
  };

  api = new API(appid, secret, getToken, saveToken);

  get_js_sdk_ticket = function(type, cb) {
    console.log('get js ticket', type);
    return Token.findOne({
      appid: appid
    }, function(err, result) {
      if (err) {
        logger.error('GetJSTicketError:' + err);
        return cb(null, null);
      } else if (result && result.js_ticket) {
        return cb(null, {
          ticket: result.js_ticket,
          expireTime: result.js_ticket_expireTime
        });
      } else {
        return cb(null, null);
      }
    });
  };

  save_js_sdk_ticket = function(type, ticket, cb) {
    console.log('save js ticket', type, ticket);
    return Token.findOne({
      appid: appid
    }, function(err, result) {
      var token;
      if (err) {
        logger.error('SaveJSTicketError:' + err);
        return cb(null, null);
      } else if (result) {
        result.js_ticket = ticket.ticket;
        result.js_ticket_expireTime = ticket.expireTime;
        return result.save(cb);
      } else {
        token = new Token({
          appid: appid,
          secret: secret,
          js_ticket: ticket.ticket,
          js_ticket_expireTime: ticket.expireTime
        });
        return token.save(cb);
      }
    });
  };

  api.registerTicketHandle(get_js_sdk_ticket, save_js_sdk_ticket);

  home_url = 'https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx147e9f502d858faa&redirect_uri=http://lovecoffee.duapp.com/init_auto&response_type=code&scope=snsapi_base&connect_redirect=1#wechat_redirect';

  menu = {
    'button': [
      {
        name: '点餐',
        type: 'view',
        url: home_url
      }
    ]
  };

  host = 'http://lovecoffee.duapp.com';

  getConfig = function(req, callback) {
    var url;
    url = host + req.url;
    console.log('url:' + url);
    return api.getJsConfig({
      debug: false,
      jsApiList: ['onMenuShareTimeline', 'onMenuShareAppMessage', 'onMenuShareQQ', 'onMenuShareWeibo'],
      url: url
    }, function(err, result) {
      return callback(err, result);
    });
  };

  inTime = function(times) {
    var now, result;
    now = moment().valueOf();
    if (!times || !times.length) {
      return false;
    } else {
      result = false;
      times.forEach(function(t) {
        var e, s;
        s = moment(t.start, 'HH:mm').valueOf();
        e = moment(t.end, 'HH:mm').valueOf();
        if (s <= now && e >= now) {
          return result = true;
        }
      });
      return result;
    }
  };

  module.exports = function(router) {
    var init;
    init = function(req, res, result) {
      var state;
      state = req.query.state;
      console.log('State:' + state);
      return User.findOne({
        openid: result.openid
      }, function(err, userResult) {
        var ep, user;
        if (err) {
          logger.error('UserFindError:' + err);
          return res.json({
            err: err
          });
        } else {
          ep = new EventProxy();
          ep.on('ok', function() {
            return getConfig(req, function(err, config) {
              if (err) {
                logger.error('ConfigError:' + err);
              }
              req.session.user = user._id;
              ep = new EventProxy();
              ep.all('products', 'pmTimes', 'pmProducts', function(products, pmTimes, pmProducts) {
                var cas, categories, dic, last_ordered, list, newPrices, ordered, pmEnabled, times;
                categories = [];
                cas = [];
                dic = {};
                list = [];
                newPrices = {};
                if (pmTimes) {
                  times = pmTimes.list;
                }
                if (pmProducts) {
                  pmProducts = pmProducts.list;
                }
                pmEnabled = inTime(times);
                if (!user.order_times) {
                  pmEnabled = false;
                }
                products.forEach(function(p) {
                  var arr, ca, index;
                  if (!dic[p.category]) {
                    dic[p.category] = [];
                  }
                  arr = dic[p.category];
                  if (pmEnabled && pmProducts && pmProducts.length) {
                    pmProducts.every(function(pm) {
                      if (p.name === pm.name) {
                        p.prices = pm.prices;
                        p.discount = true;
                        return false;
                      } else {
                        return true;
                      }
                    });
                  }
                  p.prices.reverse();
                  newPrices[p.id] = p.prices;
                  arr.push(p);
                  index = categories.indexOf(p.category);
                  if (index === -1) {
                    categories.push(p.category);
                    ca = {
                      name: p.category,
                      index: categories.indexOf(p.category)
                    };
                    cas.push(ca);
                    return list.push({
                      category: ca,
                      products: dic[p.category]
                    });
                  }
                });
                last_ordered = userResult.last_ordered;
                ordered = [];
                dic = {};
                last_ordered.forEach(function(o) {
                  var arr;
                  arr = newPrices[o.id];
                  arr.every(function(p) {
                    if (p.label === o.price_label) {
                      return o.price = p.value;
                    }
                  });
                  if (!dic[o.id]) {
                    dic[o.id] = {
                      id: o.id,
                      name: o.name,
                      detail: [
                        {
                          type: o.price_label,
                          count: o.sum,
                          price: o.price
                        }
                      ]
                    };
                    return ordered.push(dic[o.id]);
                  } else {
                    return dic[o.id].detail.push({
                      type: o.price_label,
                      count: o.sum,
                      price: o.price
                    });
                  }
                });
                return res.render('index', {
                  ordered: JSON.stringify(ordered),
                  config: config,
                  url: home_url,
                  list: list,
                  categories: cas,
                  userinfo: JSON.stringify(user)
                });
              });
              Dict.findOne({
                key: 'PMTimes'
              }, ep.done('pmTimes'));
              return Dict.findOne({
                key: 'PMProducts'
              }, ep.done('pmProducts'));
            });
          });
          user = '';
          if (userResult) {
            user = userResult;
            user.last_login = new Date();
            user.login_times++;
            return user.save(function(err, result) {
              return ep.emit('ok');
            });
          } else {
            user = new User({
              openid: result.openid,
              last_login: new Date(),
              created_at: new Date()
            });
            user.nickname = result.nickname;
            user.sex = result.sex;
            user.province = result.province;
            user.city = result.city;
            user.country = result.country;
            user.headimgurl = result.headimgurl;
            return user.save(function(err, result) {
              if (err) {
                logger.error('UserSaveError:' + err);
                return res.json({
                  err: err
                });
              } else {
                logger.trace('UserSaved:' + JSON.stringify(result));
                return ep.emit('ok');
              }
            });
          }
        }
      });
    };
    router.get('/menu', function(req, res) {
      return api.createMenu(menu, function(err, result) {
        if (err) {
          return logger.error(err);
        } else {
          logger.trace('menu setted:', result);
          return api.getMenu(function(err, result) {
            return res.json(result);
          });
        }
      });
    });
    router.get('/init_auto', function(req, res) {
      var data, headers;
      headers = req.headers;
      data = req.query;
      if (!data.code) {
        res.jsonp({
          status: false
        });
        return;
      }
      console.log('Inited2:' + JSON.stringify(data));
      return request.get('https://api.weixin.qq.com/sns/oauth2/access_token?appid=' + appid + '&secret=' + secret + '&code=' + data.code + '&grant_type=authorization_code', function(err, result) {
        var access_token, openid, refresh_token;
        if (err) {
          logger.error('UserCodeError2:' + err);
          return res.json({
            status: false
          });
        } else {
          result = JSON.parse(result.body);
          console.log('Inited2Result:' + JSON.stringify(result));
          if (result.errcode) {
            logger.error('UserCodeError2:' + result.errmsg);
            return res.json({
              status: false
            });
          } else {
            access_token = result.access_token;
            refresh_token = result.refresh_token;
            openid = result.openid;
            if (!access_token) {
              logger.error('UserAccessToeknError:' + JSON.stringify(result));
              return res.json({
                status: false
              });
            } else {
              return request.get('https://api.weixin.qq.com/sns/userinfo?access_token=' + access_token + '&openid=' + openid + '&lang=zh_CN', function(err, result) {
                var reinit;
                reinit = function() {
                  return res.redirect('https://open.weixin.qq.com/connect/oauth2/authorize?appid=' + appid + '&redirect_uri=http://lovecoffee.duapp.com/init&response_type=code&scope=snsapi_userinfo&state=' + data.state + '&connect_redirect=1#wechat_redirect');
                };
                if (err) {
                  logger.error('UserCodeError3:' + err);
                  return reinit();
                } else {
                  result = JSON.parse(result.body);
                  if (result.errcode) {
                    logger.error('UserInfoError:' + result.errmsg);
                    return reinit();
                  } else {
                    logger.trace('Init:' + JSON.stringify(result));
                    return init(req, res, result);
                  }
                }
              });
            }
          }
        }
      });
    });
    router.get('/init', function(req, res) {
      var data;
      data = req.query;
      if (!data.code) {
        res.jsonp({
          status: false
        });
        return;
      }
      return request.get('https://api.weixin.qq.com/sns/oauth2/access_token?appid=' + appid + '&secret=' + secret + '&code=' + data.code + '&grant_type=authorization_code', function(err, result) {
        var access_token, openid, refresh_token;
        if (err) {
          logger.error('UserCodeError1:' + err);
          console.log('UCErr1' + err);
          return res.jsonp({
            status: false
          });
        } else {
          result = JSON.parse(result.body);
          if (result.errcode) {
            logger.error('UserCodeError2:' + result.errmsg);
            return res.jsonp({
              status: false
            });
          } else {
            access_token = result.access_token;
            refresh_token = result.refresh_token;
            openid = result.openid;
            if (!access_token) {
              logger.error('UserAccessToeknError:' + JSON.stringify(result));
              return res.jsonp({
                status: false
              });
            } else {
              return request.get('https://api.weixin.qq.com/sns/userinfo?access_token=' + access_token + '&openid=' + openid + '&lang=zh_CN', function(err, result) {
                if (err) {
                  console.log('UCErr2' + err);
                  logger.error('UserCodeError3:' + err);
                  return res.jsonp({
                    status: false
                  });
                } else {
                  result = JSON.parse(result.body);
                  if (result.errcode) {
                    logger.error('UserInfoError:' + result.errmsg);
                    return res.jsonp({
                      status: false
                    });
                  } else {
                    return init(req, res, result);
                  }
                }
              });
            }
          }
        }
      });
    });
    router.get('/', function(req, res) {
      return res.render('login');
    });
    router.get('/test2', function(req, res) {
      return Order.find({}, {
        products: {
          $elemMatch: {
            name: req.query.name
          }
        }
      }, function(err, result) {
        return res.json({
          err: err,
          result: result
        });
      });
    });
    router.get('/pages', function(req, res) {
      return res.render('pages');
    });
    router.get('/lottery', function(req, res) {
      return res.render('lottery', {
        joined: 0
      });
    });
    router.get('/draw_lottery', function(req, res) {
      return res.render('success', {
        nums: [
          {
            value: 1234567,
            status: '未开奖'
          }
        ]
      });
    });
    router.get('/sign_up', function(req, res) {
      return res.render('sign_up');
    });
    router.post('/do_sign_up', function(req, res) {
      return res.redirect('/draw_lottery');
    });
    return router.get('/admin', auth.isAuthenticated(), function(req, res) {
      var nav;
      nav = [
        {
          path: 'dashboard',
          name: '仪表盘',
          icon: 'fa fa-dashboard'
        }, {
          path: 'lottery',
          name: '抽奖管理',
          icon: 'fa fa-list'
        }, {
          path: 'joined',
          name: '得奖管理',
          icon: 'fa fa-gift'
        }, {
          path: 'user',
          name: '用户管理',
          icon: 'fa fa-users'
        }, {
          path: 'setting',
          name: '系统设置',
          icon: 'fa fa-cogs'
        }
      ];
      return res.render('admin', {
        nav: nav
      });
    });
  };

}).call(this);
