// Generated by CoffeeScript 1.8.0
(function() {
  var Dict, auth;

  auth = require('../../lib/auth');

  Dict = require('../../models').Dict;

  module.exports = function(app) {
    app.get('/get', auth.isAuthenticated(), function(req, res) {
      var data;
      data = req.query;
      return Dict.findOne({
        key: data.key
      }, 'value list', function(err, result) {
        var arr, normal;
        if (err) {
          return res.josn({
            err: err
          });
        } else {
          if (result) {
            arr = [];
            normal = false;
            result.list.forEach(function(r) {
              if (typeof r === 'string') {
                normal = true;
                return arr.push(r);
              }
            });
            if (normal) {
              result.list = arr;
            }
          }
          return res.json({
            result: result
          });
        }
      });
    });
    return app.post('/update/list', auth.isAuthenticated(), function(req, res) {
      var data;
      console.log('update');
      data = req.body;
      delete data['_id'];
      return Dict.findOneAndUpdate({
        key: data.key
      }, data, {
        upsert: true
      }, function(err, result) {
        if (err) {
          return res.json({
            err: err
          });
        } else {
          return res.json({
            result: true
          });
        }
      });
    });
  };

}).call(this);
