// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var Log, logger, models;

  models = require('../models');

  Log = require('../models').Log;

  logger = require('log4js').getDefaultLogger();

  module.exports = {
    record: function(req, action, value, callback) {
      var ip, log;
      ip = (req.headers['x-forwarded-for'] || '').split(',')[0] || req.connection.remoteAddress;
      log = new Log({
        ip: ip,
        action: action,
        value: value
      });
      if (!callback) {
        callback = function(err, result) {
          if (err) {
            return logger.error('LogError:' + err);
          } else {
            return logger.trace('LogSaved:' + JSON.stringify(result));
          }
        };
      }
      return log.save(callback);
    }
  };

}).call(this);
