// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var MongoStore, session;

  session = require('express-session');

  MongoStore = require('connect-mongo')(session);

  module.exports = function(settings, MongoConfig) {
    settings.store = new MongoStore(MongoConfig);
    return session(settings);
  };

}).call(this);
