// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var RedisStore, session;

  session = require('express-session');

  RedisStore = require('connect-redis')(session);

  module.exports = function(settings, redisConfig) {
    settings.store = new RedisStore(redisConfig);
    return session(settings);
  };

}).call(this);
