// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var API, EventProxy, LotteryRecord, Token, User, api, appid, auth, getToken, initUser, logger, mongo, passport, saveToken, secret, sms, wechat;

  passport = require('passport');

  auth = require('./auth');

  mongo = require('./database/mongo');

  wechat = require('wechat');

  API = require('wechat-api');

  appid = 'wx1f9fe13fd3655a8d';

  secret = '2a3792094fc7e3b91a4920a8afb0a0c1';

  Token = require('../models').Token;

  User = require('../models').User;

  LotteryRecord = require('../models').LotteryRecord;

  logger = require('log4js').getDefaultLogger();

  EventProxy = require('eventproxy');

  sms = require('../lib/sms');

  getToken = function(cb) {
    return Token.findOne({
      appid: appid
    }, function(err, result) {
      if (err) {
        logger.error('GetTokenError:' + err);
        return cb(null, null);
      } else if (result) {
        if (new Date().getTime() - result.get_ts.getTime() < 300000) {
          return cb(null, {
            accessToken: result.token
          });
        } else {
          return cb(null, null);
        }
      } else {
        return cb(null, null);
      }
    });
  };

  saveToken = function(token, cb) {
    return Token.findOne({
      appid: appid
    }, function(err, result) {
      if (err) {
        cb(null, null);
        return logger.error('SaveTokenError:' + err);
      } else if (result && result.token) {
        result.token = token.accessToken;
        result.get_ts = new Date();
        return result.save(cb);
      } else {
        token = new Token({
          appid: appid,
          secret: secret,
          token: token.accessToken,
          get_ts: new Date()
        });
        return token.save(cb);
      }
    });
  };

  api = new API(appid, secret, getToken, saveToken);

  initUser = function(openid, callback) {
    return User.findOne({
      openid: openid
    }, function(err, result) {
      if (err) {
        logger.error(err);
        return callback(err);
      } else if (result) {
        logger.trace('UserInfoGot:' + JSON.stringify(result));
        return callback(null, result);
      } else {
        return api.getUser(openid, function(err, result) {
          var user;
          logger.trace('UserInfoInited:' + JSON.stringify(result));
          if (!err) {
            user = new User(result);
            user.created_at = new Date();
            return user.save(callback);
          } else {
            return callback(err);
          }
        });
      }
    });
  };

  module.exports = function(app) {
    var config;
    app.on('middleware:after:session', function(args) {
      passport.use(auth.localStrategy());
      app.use(passport.initialize());
      app.use(passport.session());
      app.use(auth.injectUser());
      app.use(function(req, res, next) {
        var onlyMobile, path, ua;
        ua = req.headers['user-agent'];
        path = req.path;
        onlyMobile = ['/auto_init', '/init', '/draw_lottery', '/share_lottery'];
        if (onlyMobile.indexOf(path) !== -1) {
          if (/mobile/i.test(ua)) {
            return next();
          } else {
            return res.send('仅支持微信浏览');
          }
        } else {
          return next();
        }
      });
      passport.serializeUser(auth.serialize);
      return passport.deserializeUser(auth.deserialize);
    });
    config = {
      token: 'wechat',
      appid: appid,
      encodingAESKey: 'YN8K5TKe0aY2fBmYGKHPpDNxu4TRnD7hSyt8wVwb3dw'
    };
    return {
      onconfig: function(config, next) {
        var Manager;
        mongo.config(config.get('mongo'));
        sms.config(config.get('sms'));
        Manager = require('../models/index').Manager;
        Manager.findOne({
          username: 'admin'
        }, function(err, result) {
          var m;
          if (!result) {
            m = new Manager({
              username: 'admin',
              password: '666666'
            });
            return m.save(function(err, result) {
              if (err) {
                return console.log(err);
              } else {
                return console.log('ManagerInited');
              }
            });
          }
        });
        return next(null, config);
      }
    };
  };

}).call(this);
