// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  define(['angular'], function(angular) {
    return angular.module('collection.service', []).service('collectionService', function() {
      var checking;
      console.group('collection service');
      console.log('inited');
      console.groupEnd();
      checking = null;
      return {
        setCheck: function(data) {
          console.group('collection service');
          console.log(data);
          console.groupEnd();
          return checking = data;
        },
        getCheck: function() {
          return checking;
        }
      };
    });
  });

}).call(this);
