// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var EventProxy, Lottery, LotteryRecord, UpdateObject, User, auth, logger, models, moment;

  models = require('../../models');

  LotteryRecord = models.LotteryRecord;

  User = models.User;

  Lottery = models.Lottery;

  UpdateObject = require('../../lib/utils').updateObject;

  auth = require('../../lib/auth');

  EventProxy = require('eventproxy');

  moment = require('moment');

  logger = require('log4js').getDefaultLogger();

  module.exports = function(router) {
    return router.get('/list', auth.isAuthenticated(), function(req, res) {
      var ca, data, ep, ep2, options, query;
      data = req.query;
      if (data.category) {
        ca = JSON.parse(data.category);
      }
      ep = new EventProxy();
      ep.all('count', 'result', function(count, result) {
        return res.json({
          count: count,
          result: result,
          pageSize: data.pageSize
        });
      });
      ep.fail(function(err) {
        logger.error(err);
        return res.json({
          err: err
        });
      });
      if (!data.pageSize) {
        data.pageSize = 10;
      }
      options = {
        sort: {
          created_at: -1
        }
      };
      if (data.page) {
        options.skip = (data.page - 1) * data.pageSize;
        options.limit = data.pageSize;
      }
      query = {};
      ep2 = new EventProxy();
      ep2.on('ok', function() {
        console.log('LRQuerry:' + JSON.stringify(query));
        LotteryRecord.find(query, null, options).exec(ep.done('result'));
        return LotteryRecord.count(query, ep.done('count'));
      });
      return ep2.emit('ok');
    });
  };

}).call(this);
