// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  define(['angular', 'console'], function(angular, console) {
    return angular.module('admin', ['ipCookie']).controller('Dashboard', function($scope, $injector) {
      return require(['controllers/dashboard'], function(controller) {
        return $injector.invoke(controller, this, {
          '$scope': $scope
        });
      });
    }).controller('User', function($scope, $injector) {
      return require(['controllers/user'], function(controller) {
        return $injector.invoke(controller, this, {
          '$scope': $scope
        });
      });
    }).controller('Setting', function($scope, $injector) {
      return require(['controllers/setting'], function(controller) {
        return $injector.invoke(controller, this, {
          '$scope': $scope
        });
      });
    }).controller('Promotion', function($scope, $injector) {
      return require(['controllers/promotion'], function(controller) {
        return $injector.invoke(controller, this, {
          '$scope': $scope
        });
      });
    }).controller('Order', function($scope, $injector) {
      return require(['controllers/order'], function(controller) {
        return $injector.invoke(controller, this, {
          '$scope': $scope
        });
      });
    }).controller('Product', function($scope, $injector) {
      return require(['controllers/product'], function(controller) {
        return $injector.invoke(controller, this, {
          '$scope': $scope
        });
      });
    }).controller('EditProduct', function($scope, $injector, data, $modalInstance) {
      return require(['controllers/edit_product'], function(controller) {
        return $injector.invoke(controller, this, {
          '$scope': $scope,
          'data': data,
          '$modalInstance': $modalInstance
        });
      });
    }).controller('EditUser', function($scope, $injector, data, $modalInstance) {
      return require(['controllers/edit_user'], function(controller) {
        return $injector.invoke(controller, this, {
          '$scope': $scope,
          'data': data,
          '$modalInstance': $modalInstance
        });
      });
    }).controller('Navigator', function($scope, $location) {
      return $scope.getStatus = function(path) {
        if ($location.path().indexOf('/' + path) !== -1) {
          return 'active';
        } else {
          return '';
        }
      };
    });
  });

}).call(this);
