// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  define(['angular', 'console'], function(angular, console) {
    return angular.module('admin', ['ipCookie']).controller('Dashboard', function($scope, $injector) {
      return require(['controllers/dashboard'], function(controller) {
        return $injector.invoke(controller, this, {
          '$scope': $scope
        });
      });
    }).controller('User', function($scope, $injector) {
      return require(['controllers/user'], function(controller) {
        return $injector.invoke(controller, this, {
          '$scope': $scope
        });
      });
    }).controller('Setting', function($scope, $injector) {
      return require(['controllers/setting'], function(controller) {
        return $injector.invoke(controller, this, {
          '$scope': $scope
        });
      });
    }).controller('Lottery', function($scope, $injector) {
      return require(['controllers/lottery'], function(controller) {
        return $injector.invoke(controller, this, {
          '$scope': $scope
        });
      });
    }).controller('EditLottery', function($scope, $injector, data, $modalInstance) {
      return require(['controllers/edit_lottery'], function(controller) {
        return $injector.invoke(controller, this, {
          '$scope': $scope,
          'data': data,
          '$modalInstance': $modalInstance
        });
      });
    }).controller('Joined', function($scope, $injector) {
      return require(['controllers/joined'], function(controller) {
        return $injector.invoke(controller, this, {
          '$scope': $scope
        });
      });
    }).controller('EditJoined', function($scope, $injector, data, $modalInstance) {
      return require(['controllers/edit_joined'], function(controller) {
        return $injector.invoke(controller, this, {
          '$scope': $scope,
          'data': data,
          '$modalInstance': $modalInstance
        });
      });
    }).controller('EditUser', function($scope, $injector, data, $modalInstance) {
      return require(['controllers/edit_user'], function(controller) {
        return $injector.invoke(controller, this, {
          '$scope': $scope,
          'data': data,
          '$modalInstance': $modalInstance
        });
      });
    }).controller('Navigator', function($scope, $location) {
      return $scope.getStatus = function(path) {
        if ($location.path().indexOf('/' + path) !== -1) {
          return 'active';
        } else {
          return '';
        }
      };
    });
  });

}).call(this);
