// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  define(['console', 'humane', 'moment'], function(console, humane, moment) {
    return function($scope, $http, data, $modalInstance) {
      console.group('edit_user');
      console.log(data);
      $scope.data = angular.copy(data);
      $scope.title = '编辑用户 ' + data.nickname;
      $scope.$apply();
      $scope.ok = function() {
        data = $scope.data;
        return $modalInstance.close(data);
      };
      $scope.cancel = function() {
        return $modalInstance.dismiss('cancel');
      };
      return console.groupEnd();
    };
  });

}).call(this);
