// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  define(['console', 'humane', 'moment'], function(console, humane, moment) {
    return function($scope, $http, data, $modalInstance) {
      console.group('edit_lottery');
      console.log(data);
      $scope.data = angular.copy(data);
      $scope.title = data ? '编辑 ' + data.name : '新增抽奖活动';
      $scope.ok = function() {
        var begin, end, right;
        data = $scope.data;
        if (!data.name || !data.begin || !data.end) {
          return humane.log('活动名称、起止时间、链接地址、分享描述均不能为空');
        } else {
          right = true;
          begin = moment(data.begin, 'YYYY-MM-DD HH:mm:ss').isValid();
          console.log(begin, data.begin);
          end = moment(data.end, 'YYYY-MM-DD HH:mm:ss').isValid();
          if (!begin || !end) {
            return humane.log('时间格式不对，需要是 2015-01-01 14:00:00 这样的');
          } else {
            return $modalInstance.close(data);
          }
        }
      };
      $scope.$watch('channel', function() {
        if (data._id) {
          return $scope.link_url = 'https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx1f9fe13fd3655a8d&redirect_uri=http://rsct.swift.tf/init_auto&state=c||' + $scope.channel + ';;p||lottery;;id||' + data._id + '&response_type=code&scope=snsapi_base&connect_redirect=1#wechat_redirect';
        }
      });
      $scope.channel = 'weixin';
      $scope.$apply();
      $scope.copyChanelUrl = function() {
        if (!data._id) {
          return humane.log('该功能需要活动保存一次后才可以使用');
        } else {
          $scope.link_url = 'https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx1f9fe13fd3655a8d&redirect_uri=http://rsct.swift.tf/init_auto&state=c||' + $scope.channel + ';;p||lottery;;id||' + data._id + '&response_type=code&scope=snsapi_base&connect_redirect=1#wechat_redirect';
          return humane.log('渠道链接已经复制好，直接粘贴使用即可');
        }
      };
      $scope.cancel = function() {
        return $modalInstance.dismiss('cancel');
      };
      return console.groupEnd();
    };
  });

}).call(this);
