// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  define(['humane', 'console'], function(humane, console) {
    var err;
    err = $('#err').text();
    if (err) {
      console.error(err);
      return humane.log(err);
    }
  });

}).call(this);
