// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  define(['angular', 'humane', 'console'], function(angular, humane, console) {
    return angular.module('login', ['ipCookie']).controller('MainCtl', function($scope, $http, ipCookie) {
      console.group('login controller');
      if (ipCookie('username')) {
        $scope.username = ipCookie('username');
        $scope.password = ipCookie('password');
        $scope.remember_me = ipCookie('remember_me');
        console.log($scope.password);
      }
      $scope.rememberChanged = function() {
        if ($scope.remember_me) {
          ipCookie('username', $scope.username);
          ipCookie('password', $scope.password);
          return ipCookie('remember_me', $scope.remember_me);
        } else {
          ipCookie.remove('username');
          ipCookie.remove('password');
          return ipCookie.remove('remember_me');
        }
      };
      $scope.signIn = function() {
        ipCookie.remove('username');
        ipCookie.remove('password');
        ipCookie.remove('remember_me');
        ipCookie('username', $scope.username);
        ipCookie('password', $scope.password);
        return ipCookie('remember_me', $scope.remember_me);
      };
      return console.groupEnd();
    });
  });

}).call(this);
