// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  define(['console', 'humane', 'moment'], function(console, humane, moment) {
    return function($scope, $http, uiGridConstants, $modal, $interval, $location) {
      var caching;
      console.group('sms');
      $scope.page = 1;
      $scope.search = function() {
        $scope.page = 1;
        return $scope.getData();
      };
      $scope.pageSize = 10;
      $scope.pages = [10, 25, 50, 100];
      $scope.footer = 'partials/grid/grid_footer.html';
      $scope.header = 'partials/grid/grid_header.html';
      $scope.$watch('pageSize', function(n) {
        return $scope.getData();
      });
      $scope.$watch('page', function(n) {
        return $scope.getData();
      });
      caching = [];
      $scope.requesting = false;
      $scope.externalScopes = $scope.gridOptions = {
        enableSorting: false,
        columnDefs: [
          {
            name: '手机号',
            field: 'mobile',
            width: 100,
            enableSorting: false
          }, {
            name: '内容',
            field: 'content',
            enableSorting: false
          }, {
            name: '时间',
            field: 'created_at',
            width: 200,
            enableSorting: false
          }
        ]
      };
      $scope.getData = function() {
        if ($scope.requesting) {
          return;
        }
        $scope.requesting = true;
        return $http.get('/m/sms/list', {
          params: {
            page: $scope.page,
            pageSize: $scope.pageSize,
            mobile: $scope.keywords
          }
        }).success(function(result) {
          console.group('sms');
          console.log('GotSMS', result);
          console.groupEnd();
          $scope.requesting = false;
          if (result.err) {
            return humane.log(result.err);
          } else {
            $scope.count = result.count;
            if (result.result) {
              result.result.forEach(function(r) {
                return r.created_at = moment(r.creatd_at).format('YYYY-MM-DD HH:MM:SS');
              });
            }
            return $scope.gridOptions.data = result.result;
          }
        }).error(function(err) {
          $scope.requesting = false;
          if (err) {
            return humane.log(err);
          }
        });
      };
      $scope.getData();
      return console.groupEnd();
    };
  });

}).call(this);
