// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  define(['angular', 'controllers/admin', 'controllers/error', 'angular-route', 'angular-ui-grid', 'angular-bootstrap', 'global', 'services/collection_service', 'ng-tags-input'], function(angular) {
    var app;
    app = angular.module('MainApp', ['ngRoute', 'ui.grid', 'ui.bootstrap', 'ipCookie', 'admin', 'collection.service', 'ngTagsInput']);
    app.init = function() {
      return angular.bootstrap(document, ['MainApp']);
    };
    return app;
  });

}).call(this);
