// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  define(['angular', 'controllers/login', 'controllers/error'], function(angular) {
    var app;
    app = angular.module('MainApp', ['login', 'ipCookie']);
    app.init = function() {
      return angular.bootstrap(document, ['MainApp']);
    };
    return app;
  });

}).call(this);
