// Generated by CoffeeScript 1.8.0
(function() {
  var handleComplete, handleProgress, load, manifest1;

  manifest1 = [
    {
      src: "1.jpg"
    }, {
      src: "2.jpg"
    }
  ];

  handleProgress = function(event) {
    var percent;
    percent = event.loaded;
    console.log('P:' + percent);
    return $('#loading-label').text(Math.round(percent * 100) + '%');
  };

  handleComplete = function(event) {
    return console.log('Loaded');
  };

  load = function() {
    var preload;
    preload = new createjs.LoadQueue();
    preload.on("progress", handleProgress);
    preload.on("complete", handleComplete);
    return preload.loadManifest(manifest1, true, 'imgages/');
  };

}).call(this);
