// Generated by CoffeeScript 1.8.0
(function() {
  var fnOut, fnOver, w;

  fnOver = function() {
    if ($(this).attr('clickable')) {
      $(this).addClass('onclick');
    }
    return $(this).addClass('active');
  };

  fnOut = function() {
    if ($(this).attr('clickable')) {
      $(this).removeClass('onclick');
    }
    return $(this).removeClass('active');
  };

  $('.front').hover(fnOver, fnOut);

  w = $('.s4-img').width();

  $('.s4-img').animate({
    left: -w,
    opacity: 0
  }, {
    duration: 300
  });

}).call(this);
