// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var DictSchema, Mongoose, Schema, Timestamps;

  Mongoose = require('mongoose');

  Schema = Mongoose.Schema;

  DictSchema = new Schema({
    key: {
      type: String,
      required: true,
      index: {
        unique: true
      }
    },
    value: String,
    list: []
  });

  Timestamps = require('mongoose-times');

  DictSchema.plugin(Timestamps, {
    created: "created_at",
    lastUpdated: "updated_at"
  });

  Mongoose.model('Dict', DictSchema);

}).call(this);
