// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var Mongoose, SMSSchema, Schema;

  Mongoose = require('mongoose');

  Schema = Mongoose.Schema;

  SMSSchema = new Schema({
    mobile: Number,
    content: String,
    created_at: Date
  });

  Mongoose.model('SMS', SMSSchema);

}).call(this);
