// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var Mongoose, Schema, UserSchema;

  Mongoose = require('mongoose');

  Schema = Mongoose.Schema;

  UserSchema = new Schema({
    openid: {
      type: String,
      index: {
        unique: true
      }
    },
    nickname: String,
    truename: String,
    birthday: Date,
    address: String,
    addresses: [],
    sex: String,
    province: String,
    city: String,
    country: String,
    subscribe_time: String,
    remark: String,
    headimgurl: String,
    mobile: {
      type: String,
      index: true
    },
    mobile2: String,
    verify_code: String,
    score: Number,
    order_times: {
      type: Number,
      "default": 0
    },
    login_times: {
      type: Number,
      "default": 0
    },
    registered: {
      type: Boolean,
      "default": false
    },
    channel: String,
    channels: [String],
    access_token: String,
    refresh_token: String,
    expires_in: Number,
    scope: String,
    token_created_at: Date,
    wx_status: String,
    last_login: Date,
    created_at: Date
  });

  Mongoose.model('User', UserSchema);

}).call(this);
